// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZ0VUHWQ4mVV3IEGoTTqBBs03Ezxk6xs',
    appId: '1:1090706602519:web:4bf34aa77c390cb7e5ba52',
    messagingSenderId: '1090706602519',
    projectId: 'mad-hms',
    authDomain: 'mad-hms.firebaseapp.com',
    storageBucket: 'mad-hms.firebasestorage.app',
    measurementId: 'G-N1G5JHGZ0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3TcaEzP_ajKmga6Z0qn7AdZ9owf6B8Jo',
    appId: '1:1090706602519:android:36fb309dddb2135de5ba52',
    messagingSenderId: '1090706602519',
    projectId: 'mad-hms',
    storageBucket: 'mad-hms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMF5PIMQQ0gAAuAWsOIhRRk7C4mzv6V0',
    appId: '1:1090706602519:ios:75376bd5c4c26d91e5ba52',
    messagingSenderId: '1090706602519',
    projectId: 'mad-hms',
    storageBucket: 'mad-hms.firebasestorage.app',
    iosBundleId: 'com.example.madHms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCMF5PIMQQ0gAAuAWsOIhRRk7C4mzv6V0',
    appId: '1:1090706602519:ios:75376bd5c4c26d91e5ba52',
    messagingSenderId: '1090706602519',
    projectId: 'mad-hms',
    storageBucket: 'mad-hms.firebasestorage.app',
    iosBundleId: 'com.example.madHms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyZ0VUHWQ4mVV3IEGoTTqBBs03Ezxk6xs',
    appId: '1:1090706602519:web:1946b5882cfc7364e5ba52',
    messagingSenderId: '1090706602519',
    projectId: 'mad-hms',
    authDomain: 'mad-hms.firebaseapp.com',
    storageBucket: 'mad-hms.firebasestorage.app',
    measurementId: 'G-C69FCYPJ2B',
  );
}
